apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: lyrics-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /lyrics-scraper
        backend:
          serviceName: lyrics-scraper
          servicePort: 80

      - path: /
        backend:
          serviceName: lyrics-scraper
          servicePort: 80
